services:
  db:
    image: postgres:16
    container_name: notes-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
