spring:
  datasource:
    url: jdbc:h2:mem:notesdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate.ddl-auto: update   # dev-only
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console.enabled: true
server:
  port: 8080
